; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
name = SkiBeanComm

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
framework = arduino
extra_scripts = post:scripts/merge_firmware.py
lib_deps = 
	br3ttb/PID@^1.2.1
	h2zero/NimBLE-Arduino@^2.3.7
	pstolarz/OneWireNg

[env:esp32-c6-devkitc-1-CT1780]
board = esp32-c6-devkitc-1
monitor_speed = 115200
monitor_filters = time, log2file
build_flags =
    -Wall
	-Wextra
	-D RGB_BUILTIN_LED_COLOR_ORDER=LED_COLOR_ORDER_GRB
	-D ARDUINO_USB_CDC_ON_BOOT=0
	-D ARDUINO_USB_MODE=0
	-D CORE_DEBUG_LEVEL=3
	-D TX_PIN=12
	-D RX_PIN=13
	-D CT1780_PIN=2

[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
build_flags =
	-D TX_PIN=19
	-D RX_PIN=20

[env:esp32-s3-zero]
board = waveshare_esp32_s3_zero
build_flags =
	-D TX_PIN=19
	-D RX_PIN=20

[env:esp32-c3-super-mini]
board = esp32-c3-devkitm-1
build_flags =
	-D TX_PIN=18
	-D RX_PIN=19